### ISSUE TITLE
Viết testcase cho màn hình đăng ký 

### ISSUE THREAD

**Issue by tamntt-relipa** [relipasoft/religram-react#3]
# Mô tả
## `[PM]` Mục đích của việc tạo issue `Required`
- Đảm bảo chất lượng dự án

## `[PM]` Yêu cầu và mong muốn đạt được của issue 
- Viết testcase bao phủ chức năng đăng ký user cho hệ thống

## `[PM]` Tiêu chuẩn nghiệm thu (Mức User Acceptance Test) `Required`
- [ ] Code đã selftest chưa
- [ ] Code đã được review
- [ ] Đã viết UT
- [ ] Đã có AT
- [ ] Đã có testcase result chưa

## `[Developer]` Mô tả cách làm dự kiến và thời gian estimate tương ứng. Tối đa 4h cho 1 gạch đầu dòng `Required`
- Viết testcase kiểm tra giao diện 
- Viết testcase cho chức năng đăng ký bằng email
- Viết testcase cho chức năng đăng ký bằng fb 

## `[Cả team]` Rủi ro có thể xảy ra với phương án trên. Cần mở tài liệu dự án để tham khảo cho chắc chắn `Required`
-   

# Ghi chép chi tiết khi thực hiện task `Required all`
## `[Tester]` Testcase Result 
- Link: https://docs.google.com/spreadsheets/d/1BzAGGiZAP6qQYbhPz6eJB5ybVHSdHGBw9XgL4aZxjVg/edit#gid=1614315577

## `[Developer]` Danh sách các màn hình hoặc chức năng bị ảnh hưởng bởi việc sửa đổi này
-  Màn hình đăng ký

## `[Developer]` Release notes
-

**Comment by hoainv-relipasoft** [comment]
@tamntt-relipa về testcasse thì cũng OK rồi đấy, tớ có comment 1 vài chỗ đó

**Comment by tamntt-relipa** [comment]
@hoainv-relipasoft T đã xem lại và update comment
