### ISSUE TITLE
Viết testcase cho màn hình đăng nhập

### ISSUE THREAD

**Issue by tamntt-relipa** [relipasoft/religram-react#4]
# Mô tả
## `[PM]` Mục đích của việc tạo issue `Required`
- Đảm bảo chất lượng dự án

## `[PM]` Yêu cầu và mong muốn đạt được của issue 
- Viết testcase bao phủ chức năng đăng nhập cho hệ thống

## `[PM]` Tiêu chuẩn nghiệm thu (Mức User Acceptance Test) `Required`
- [ ] Code đã selftest chưa
- [ ] Code đã được review
- [ ] Đã viết UT
- [ ] Đã có AT
- [ ] Đã có testcase result chưa

## `[Developer]` Mô tả cách làm dự kiến và thời gian estimate tương ứng. Tối đa 4h cho 1 gạch đầu dòng `Required`
- Viết testcase kiểm tra giao diện
- Viết testcase đăng nhập bằng email
- Viết testcase đăng nhập bằng fb

## `[Cả team]` Rủi ro có thể xảy ra với phương án trên. Cần mở tài liệu dự án để tham khảo cho chắc chắn `Required`
-   

# Ghi chép chi tiết khi thực hiện task `Required all`
## `[Tester]` Testcase Result 
- Link: https://docs.google.com/spreadsheets/d/1BzAGGiZAP6qQYbhPz6eJB5ybVHSdHGBw9XgL4aZxjVg/edit#gid=413939138

## `[Developer]` Danh sách các màn hình hoặc chức năng bị ảnh hưởng bởi việc sửa đổi này
-  

## `[Developer]` Release notes
-

**Comment by hoainv-relipasoft** [comment]
@tamntt-relipa Phần login với FB tớ đang thấy có vẻ không ổn lắm nhỉ?
Tớ đang hình dung khi người dùng ấn vào nút "Login with Facebook" thì sẽ có 2 pattern chính:
- User đã đăng ký tài khoản bằng FB => Xác thực rồi vào màn hình home
- User chưa từng đăng ký bằng FB => Redirect sang màn hình đăng ký User bằng FB chứ nhỉ
Còn mấy cái cậu đang nêu thì hơi giống kiểu test chức năng đăng nhập của bên FB ấy :D

**Comment by tamntt-relipa** [comment]
@hoainv-relipasoft t đã hiểu và update lại. thanks c
