### ISSUE TITLE
Viết test case cho màn hình detail post và comment

### ISSUE THREAD

**Issue by tamntt-relipa** [relipasoft/religram-react#9]
# Mô tả
## `[PM]` Mục đích của việc tạo issue `Required`
- Đảm bảo chất lượng dự án

## `[PM]` Yêu cầu và mong muốn đạt được của issue 
- Viết testcase bao phủ chức năng đăng nhập cho hệ thống

## `[PM]` Tiêu chuẩn nghiệm thu (Mức User Acceptance Test) `Required`
- [ ] Code đã selftest chưa
- [ ] Code đã được review
- [ ] Đã viết UT
- [ ] Đã có AT
- [ ] Đã có testcase result chưa

## `[Developer]` Mô tả cách làm dự kiến và thời gian estimate tương ứng. Tối đa 4h cho 1 gạch đầu dòng `Required`
- Viết test case kiểm tra giao diện
- Viết test case kiểm tra chức năng Like/Unlike bài viết
- Viết test case kiểm tra chức năng post bài viết
- Viết test case kiểm tra chức năng comment bài viết 

## `[Cả team]` Rủi ro có thể xảy ra với phương án trên. Cần mở tài liệu dự án để tham khảo cho chắc chắn `Required`
-   

# Ghi chép chi tiết khi thực hiện task `Required all`
## `[Tester]` Testcase Result 
- Link: https://docs.google.com/spreadsheets/d/1BzAGGiZAP6qQYbhPz6eJB5ybVHSdHGBw9XgL4aZxjVg/edit?ts=5d4aa9df#gid=896308300

## `[Developer]` Danh sách các màn hình hoặc chức năng bị ảnh hưởng bởi việc sửa đổi này
-  

## `[Developer]` Release notes
-

**Comment by hoainv-relipasoft** [comment]
@tamntt-relipa xem lại giúp tớ mấy chỗ comment nhé
